=== Alejandr024/LM/Retos/B5/nomina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="nomina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="puesto" type="xs:string"/>
                            <xs:element name="salario_base" type="xs:decimal"/>
                            <xs:element name="transporte" type="xs:decimal"/>
                            
                            <xs:element name="complemento_variable">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="retenciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="seguridad_social" type="xs:decimal"/>
                                        <xs:element name="irpf" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="salario_bruto" type="xs:decimal"/>
                            <xs:element name="salario_neto" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Alejandr024/LM/Retos/B5/nomina.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="nomina.xsl"?>
<nomina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nomina.xsd">
    <empleado id="E001">
    <nombre>Laura Martínez</nombre>
    <puesto>Administrativa</puesto>
    <salario_base>1600.00</salario_base>
    <transporte>100.00</transporte>
    <complemento_variable>
    <tipo>Productividad</tipo>
    <cantidad>150.00</cantidad>
    </complemento_variable>
    <retenciones>
    <seguridad_social>120.00</seguridad_social>
    <irpf>180.00</irpf>
    </retenciones>
    <salario_bruto>1850.00</salario_bruto>
    <salario_neto>1550.00</salario_neto>
    </empleado>
</nomina>
